#!/usr/bin/env bash

# Store the current directory in a variable
project_dir=$(pwd)

# first argument should be the directory of the example
cd $1

# terraform setup
terraform init
terraform plan -out tfplan.binary
terraform show -json tfplan.binary > tfplan.json

# infracost setup
infracost breakdown --sync-usage-file --usage-file infracost-usage.yml --path .

# run analysis
cd $project_dir
poetry run iac-analysis --debug check $1/tfplan.json $1/infracost-usage.yml